import type { Book, Question } from '../types'

export const questions: Question[] = [
  {
    id: 'ink-001', subjectId: 'inkilap', topic: 'Bir Kahraman Doğuyor', difficulty: 1,
    stem: 'Mustafa Kemal’in doğduğu şehir ve yıl aşağıdakilerden hangisidir?',
    options: ['Manastır – 1880', 'Selanik – 1881', 'İstanbul – 1881', 'Sofya – 1883'],
    answer: 1,
    explanation: 'Mustafa Kemal 1881 yılında, o dönem Osmanlı toprağı olan Selanik’te doğmuştur. Selanik’in çok kültürlü ve canlı yapısı fikir dünyasını etkilemiştir.',
  },
  {
    id: 'ink-002', subjectId: 'inkilap', topic: 'Bir Kahraman Doğuyor', difficulty: 2,
    stem: 'Mustafa Kemal’in askerî öğrenimi sırasında matematik öğretmeni tarafından kendisine “Kemal” adının verilmesinin nedeni nedir?',
    options: [
      'Babasının vasiyeti olduğu için',
      'Olgunluğu ve matematikteki başarısı nedeniyle, adaşından ayırt etmek için',
      'Padişahın emriyle',
      'Okul yönetmeliği gereği',
    ],
    answer: 1,
    explanation: 'Matematik öğretmeni Mustafa Sabri Bey, kendi adı da Mustafa olduğu için onu ayırt etmek ve olgunluğunu (kemal) vurgulamak amacıyla “Kemal” adını vermiştir.',
  },
  {
    id: 'ink-003', subjectId: 'inkilap', topic: 'Bir Kahraman Doğuyor', difficulty: 2,
    stem: 'Mustafa Kemal’in Çanakkale Savaşı’ndaki “Ben size taarruzu değil, ölmeyi emrediyorum” sözü hangi özelliğini yansıtır?',
    options: ['Vatanseverliği ve liderliği', 'İnkılapçılığı', 'Barışçılığı', 'Eğitimciliği'],
    answer: 0,
    explanation: 'Bu söz, Conkbayırı’nda kritik anda söylenmiştir ve Mustafa Kemal’in vatan savunmasındaki kararlılığını, askerlerine güven veren liderliğini gösterir.',
  },
  {
    id: 'ink-004', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 1,
    stem: 'Mondros Ateşkes Antlaşması hangi tarihte imzalanmıştır?',
    options: ['30 Ekim 1918', '11 Kasım 1918', '10 Ağustos 1920', '24 Temmuz 1923'],
    answer: 0,
    explanation: 'Mondros Ateşkes Antlaşması 30 Ekim 1918’de Limni Adası’nın Mondros Limanı’nda imzalanmış ve Osmanlı Devleti fiilen sona ermiştir.',
  },
  {
    id: 'ink-005', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 3,
    stem: 'Mondros Ateşkes Antlaşması’nın 7. maddesi (“İtilaf Devletleri güvenliklerini tehdit eden bir durumda herhangi bir stratejik noktayı işgal edebilecek”) hangi sonuca yol açmıştır?',
    options: [
      'Osmanlı ordusunun güçlenmesine',
      'İşgallere hukuki kılıf hazırlanmasına',
      'Kapitülasyonların kaldırılmasına',
      'Boğazların Türk yönetimine bırakılmasına',
    ],
    answer: 1,
    explanation: '7. madde, İtilaf Devletlerine istedikleri yeri işgal etme imkânı tanımıştır. Bu madde dayanak gösterilerek Anadolu’nun birçok bölgesi işgal edilmiştir.',
  },
  {
    id: 'ink-006', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 2,
    stem: 'Mustafa Kemal’in 19 Mayıs 1919’da Samsun’a çıkışının resmî görevi neydi?',
    options: [
      'Doğu Anadolu’da ordu kurmak',
      '9. Ordu Müfettişi olarak bölgedeki asayişsizliği gidermek',
      'İstanbul Hükûmeti adına barış görüşmeleri yapmak',
      'Kuvâ-yı Milliye’yi lağvetmek',
    ],
    answer: 1,
    explanation: 'Mustafa Kemal, 9. Ordu Müfettişi sıfatıyla bölgedeki karışıklıkları gidermek ve silahları toplamak üzere görevlendirilmiştir. Ancak bu görevi millî mücadeleyi başlatmak için kullanmıştır.',
  },
  {
    id: 'ink-007', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 2,
    stem: '“Millî sınırlar içinde vatan bir bütündür, parçalanamaz.” kararı ilk kez hangi genelgede yer almıştır?',
    options: ['Amasya Genelgesi', 'Erzurum Kongresi', 'Sivas Kongresi', 'Havza Genelgesi'],
    answer: 1,
    explanation: 'Bu karar Erzurum Kongresi’nde (23 Temmuz – 7 Ağustos 1919) alınmış, daha sonra Sivas Kongresi’nde tüm yurdu kapsayacak biçimde tekrarlanmıştır.',
  },
  {
    id: 'ink-008', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 3,
    stem: 'Amasya Genelgesi’nin “Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.” maddesi neyi ifade eder?',
    options: [
      'Saltanatın devam edeceğini',
      'Kurtuluşun ancak millî egemenlikle sağlanacağını',
      'İtilaf Devletlerinden yardım isteneceğini',
      'Manda ve himayenin kabul edildiğini',
    ],
    answer: 1,
    explanation: 'Bu madde, millî egemenlik fikrinin ilk kez resmî bir belgede dile getirilmesidir. Kurtuluşun dış güçlere değil, milletin kendi kararına bağlı olduğu vurgulanır.',
  },
  {
    id: 'ink-009', subjectId: 'inkilap', topic: 'Millî Uyanış', difficulty: 2,
    stem: 'Sivas Kongresi’nin Erzurum Kongresi’nden en önemli farkı nedir?',
    options: [
      'Yalnızca Doğu illerini kapsaması',
      'Toplanış biçimi bakımından millî, aldığı kararlar bakımından da millî olması',
      'Padişah tarafından toplanmış olması',
      'Manda ve himayenin kabul edilmesi',
    ],
    answer: 1,
    explanation: 'Erzurum Kongresi toplanış bakımından bölgesel, kararları bakımından millîdir. Sivas Kongresi ise hem toplanış hem kararlar bakımından millîdir; tüm yurttan delegeler katılmıştır.',
  },
  {
    id: 'ink-010', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 1,
    stem: 'Türkiye Büyük Millet Meclisi hangi tarihte açılmıştır?',
    options: ['19 Mayıs 1919', '23 Nisan 1920', '29 Ekim 1923', '30 Ağustos 1922'],
    answer: 1,
    explanation: 'TBMM 23 Nisan 1920’de Ankara’da açılmıştır. Bu tarih, millî egemenliğe dayalı yeni Türk devletinin temelini oluşturur.',
  },
  {
    id: 'ink-011', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 2,
    stem: 'Aşağıdaki cephelerden hangisi Kurtuluş Savaşı’nın Doğu Cephesi’dir?',
    options: ['Yunanlılara karşı açılan cephe', 'Ermenilere karşı açılan cephe', 'Fransızlara karşı açılan cephe', 'İngilizlere karşı açılan cephe'],
    answer: 1,
    explanation: 'Doğu Cephesi’nde Kâzım Karabekir komutasında Ermenilere karşı savaşılmış, 3 Aralık 1920 Gümrü Antlaşması ile bu cephe kapanmıştır.',
  },
  {
    id: 'ink-012', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 2,
    stem: 'TBMM’nin uluslararası alanda ilk siyasi başarısı ve tanınması hangi antlaşmayla olmuştur?',
    options: ['Gümrü Antlaşması', 'Moskova Antlaşması', 'Ankara Antlaşması', 'Mudanya Ateşkesi'],
    answer: 0,
    explanation: 'Gümrü Antlaşması (3 Aralık 1920), TBMM’nin imzaladığı ilk antlaşmadır ve TBMM’nin ilk siyasi ve askerî başarısı olarak kabul edilir.',
  },
  {
    id: 'ink-013', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 3,
    stem: 'Sakarya Meydan Muharebesi’nin sonuçları arasında aşağıdakilerden hangisi yer almaz?',
    options: [
      '1683 Viyana bozgunundan beri süren geri çekilişin sona ermesi',
      'Mustafa Kemal’e “Gazi” unvanı ve mareşallik rütbesi verilmesi',
      'Fransa ile Ankara Antlaşması’nın imzalanması',
      'Yunan ordusunun İzmir’den tamamen atılması',
    ],
    answer: 3,
    explanation: 'Yunan ordusunun İzmir’den atılması Büyük Taarruz (26 Ağustos – 9 Eylül 1922) sonucudur. Sakarya sonrası savunma dönemi bitmiş, taarruz dönemi başlamıştır.',
  },
  {
    id: 'ink-014', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 2,
    stem: 'Lozan Barış Antlaşması’nda çözüme kavuşturulamayan ve sonraya bırakılan konu hangisidir?',
    options: ['Kapitülasyonlar', 'Musul sorunu', 'Azınlıklar', 'Savaş tazminatı'],
    answer: 1,
    explanation: 'Musul sorunu Lozan’da çözülememiş, İngiltere ile ikili görüşmelere bırakılmıştır. 1926 Ankara Antlaşması ile Musul Irak’a bırakılmıştır.',
  },
  {
    id: 'ink-015', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 1,
    stem: 'Saltanat hangi tarihte kaldırılmıştır?',
    options: ['1 Kasım 1922', '29 Ekim 1923', '3 Mart 1924', '20 Nisan 1924'],
    answer: 0,
    explanation: 'Saltanat 1 Kasım 1922’de kaldırılmıştır. Böylece Lozan’a tek temsilci gönderilmesi sağlanmış ve millî egemenlik yolunda önemli bir adım atılmıştır.',
  },
  {
    id: 'ink-016', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 2,
    stem: '3 Mart 1924’te gerçekleştirilen inkılaplar arasında aşağıdakilerden hangisi yoktur?',
    options: [
      'Halifeliğin kaldırılması',
      'Tevhid-i Tedrisat Kanunu’nun kabulü',
      'Şer’iye ve Evkaf Vekâleti’nin kaldırılması',
      'Medeni Kanun’un kabulü',
    ],
    answer: 3,
    explanation: 'Türk Medeni Kanunu 17 Şubat 1926’da kabul edilmiştir. 3 Mart 1924’te halifelik kaldırılmış, öğretim birleştirilmiş ve Şer’iye Vekâleti kapatılmıştır.',
  },
  {
    id: 'ink-017', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 2,
    stem: 'Kadınlara milletvekili seçme ve seçilme hakkı hangi yıl verilmiştir?',
    options: ['1930', '1933', '1934', '1935'],
    answer: 2,
    explanation: 'Kadınlara 1930’da belediye seçimlerine, 1933’te muhtarlık seçimlerine, 5 Aralık 1934’te ise milletvekili seçme ve seçilme hakkı tanınmıştır.',
  },
  {
    id: 'ink-018', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 3,
    stem: '“Egemenlik kayıtsız şartsız milletindir.” ilkesi Atatürk ilkelerinden hangisiyle doğrudan ilgilidir?',
    options: ['Laiklik', 'Cumhuriyetçilik', 'Devletçilik', 'İnkılapçılık'],
    answer: 1,
    explanation: 'Cumhuriyetçilik, egemenliğin millete ait olduğu ve yöneticilerin seçimle iş başına geldiği yönetim biçimini benimser.',
  },
  {
    id: 'ink-019', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 2,
    stem: 'Aşağıdaki inkılaplardan hangisi doğrudan laiklik ilkesiyle ilişkilidir?',
    options: [
      'Soyadı Kanunu’nun kabulü',
      'Tekke, zaviye ve türbelerin kapatılması',
      'Ölçü birimlerinin değiştirilmesi',
      'Kılık kıyafette düzenleme',
    ],
    answer: 1,
    explanation: 'Tekke, zaviye ve türbelerin kapatılması (30 Kasım 1925), dinî kurumların devlet işlerinden ayrılması ve toplumsal hurafelerle mücadele amacı taşır; doğrudan laiklikle ilişkilidir.',
  },
  {
    id: 'ink-020', subjectId: 'inkilap', topic: 'Çağdaş Türkiye', difficulty: 2,
    stem: 'Montrö Boğazlar Sözleşmesi ile ne sağlanmıştır?',
    options: [
      'Hatay’ın anavatana katılması',
      'Boğazlar üzerinde Türkiye’nin tam egemenliğinin tanınması',
      'Musul’un Türkiye’ye bırakılması',
      'Kapitülasyonların kaldırılması',
    ],
    answer: 1,
    explanation: '20 Temmuz 1936’da imzalanan Montrö Boğazlar Sözleşmesi ile Boğazlar Komisyonu kaldırılmış ve Boğazlar tamamen Türkiye’nin egemenliğine bırakılmıştır.',
  },
  {
    id: 'ink-021', subjectId: 'inkilap', topic: 'Çağdaş Türkiye', difficulty: 3,
    stem: 'Hatay’ın anavatana katılması hangi yıl gerçekleşmiştir?',
    options: ['1936', '1938', '1939', '1940'],
    answer: 2,
    explanation: 'Hatay, 29 Haziran 1939’da TBMM kararıyla Türkiye’ye katılmıştır. Atatürk bu süreci başlatmış ancak sonucunu göremeden 10 Kasım 1938’de vefat etmiştir.',
  },
  {
    id: 'ink-022', subjectId: 'inkilap', topic: 'Çağdaş Türkiye', difficulty: 1,
    stem: 'Atatürk hangi tarihte vefat etmiştir?',
    options: ['29 Ekim 1938', '10 Kasım 1938', '19 Mayıs 1939', '23 Nisan 1938'],
    answer: 1,
    explanation: 'Mustafa Kemal Atatürk 10 Kasım 1938 saat 09.05’te Dolmabahçe Sarayı’nda vefat etmiştir.',
  },
  {
    id: 'ink-023', subjectId: 'inkilap', topic: 'Atatürkçülük', difficulty: 3,
    stem: '“Yurtta sulh, cihanda sulh” ilkesi Atatürk dönemi dış politikasının hangi özelliğini yansıtır?',
    options: [
      'Yayılmacı bir politika izlendiğini',
      'Barışçı ve gerçekçi bir politika izlendiğini',
      'Tarafsız kalındığını',
      'Askerî ittifaklardan uzak durulduğunu',
    ],
    answer: 1,
    explanation: 'Bu ilke, hem iç barışın hem dünya barışının korunmasını hedefler. Balkan Antantı ve Sadabat Paktı bu barışçı politikanın somut örnekleridir.',
  },
  {
    id: 'ink-024', subjectId: 'inkilap', topic: 'Millî Bir Destan', difficulty: 3,
    stem: 'Tekâlif-i Milliye Emirleri hangi savaş öncesinde yayımlanmıştır?',
    options: ['I. İnönü', 'II. İnönü', 'Sakarya', 'Büyük Taarruz'],
    answer: 2,
    explanation: 'Tekâlif-i Milliye (Millî Yükümlülükler) Emirleri, Sakarya Meydan Muharebesi öncesinde 7-8 Ağustos 1921’de ordunun ihtiyaçlarını karşılamak için yayımlanmıştır.',
  },
]

export const book: Book = {
  id: 'inkilap-8',
  subjectId: 'inkilap',
  title: 'T.C. İnkılap Tarihi 8 — Bir Milletin Uyanışı',
  subtitle: 'LGS Konu Anlatımı ve Kronoloji Rehberi',
  author: 'Ali Kerem Yayınları Sosyal Bilimler Kurulu',
  edition: '1. Baskı',
  year: 2026,
  blurb:
    'Tarihi tarih ezberi olmaktan çıkaran bir anlatım. Her olay bir “neden” ve bir “sonuç” ile bağlanıyor; kronoloji şeritleriyle bütün resim görülüyor.',
  chapters: [
    {
      id: 'ink-u1',
      title: '1. Ünite — Bir Kahraman Doğuyor ve Millî Uyanış',
      pages: [
        {
          id: 'ink-u1-p1', kind: 'content',
          title: 'Bir Kahraman Doğuyor',
          subtitle: 'Selanik’ten Çanakkale’ye',
          blocks: [
            { id: 'b1', type: 'p', text: 'Mustafa Kemal 1881’de Selanik’te doğdu. Babası Ali Rıza Efendi gümrük memuru ve kereste tüccarı, annesi Zübeyde Hanım geleneksel değerlere bağlı bir kadındı. Selanik; farklı dinlerin, dillerin ve fikirlerin bir arada yaşadığı, Avrupa’ya açılan bir liman kentiydi. Bu çok kültürlü ortam, Mustafa Kemal’in fikir dünyasını doğrudan etkiledi.' },
            {
              id: 'b2', type: 'timeline',
              items: [
                { date: '1881', text: 'Selanik’te doğdu.' },
                { date: '1893', text: 'Selanik Askerî Rüştiyesi’ne girdi; “Kemal” adını burada aldı.' },
                { date: '1899', text: 'İstanbul Harp Okulu’na başladı.' },
                { date: '1905', text: 'Kurmay yüzbaşı olarak Harp Akademisi’nden mezun oldu.' },
                { date: '1911-12', text: 'Trablusgarp Savaşı’nda Derne ve Tobruk’ta görev aldı.' },
                { date: '1915', text: 'Çanakkale Savaşı — Anafartalar Grup Komutanı.' },
                { date: '1916', text: 'Muş ve Bitlis’i geri aldı, tümgeneral (mirliva) oldu.' },
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'bilgi', title: 'Neden “Kemal”?',
              text: 'Matematik öğretmeni Mustafa Sabri Bey, kendi adı da Mustafa olduğu için öğrencisini ayırt etmek istedi. Olgunluğunu ve başarısını takdir ettiği için ona “Kemal” (olgunluk, yetkinlik) adını verdi.',
            },
            { id: 'b4', type: 'h3', text: 'Fikir Hayatını Etkileyen Kaynaklar' },
            {
              id: 'b5', type: 'list',
              items: [
                'Namık Kemal — vatan ve hürriyet fikri',
                'Ziya Gökalp — Türkçülük ve sosyoloji',
                'Tevfik Fikret — akılcılık ve ilerleme',
                'Mehmet Emin Yurdakul — sade dil ve millî şiir',
                'Jean-Jacques Rousseau, Montesquieu, Voltaire — halk egemenliği ve aydınlanma',
              ],
            },
            {
              id: 'b6', type: 'quote',
              text: 'Ben size taarruzu emretmiyorum, ölmeyi emrediyorum! Biz ölünceye kadar geçecek zaman zarfında, yerimize başka kuvvetler ve kumandanlar geçebilir.',
              source: 'Mustafa Kemal, Conkbayırı – 1915',
            },
          ],
        },
        {
          id: 'ink-u1-p2', kind: 'content',
          title: 'I. Dünya Savaşı ve Mondros',
          subtitle: 'Bir imparatorluğun son perdesi',
          blocks: [
            { id: 'b1', type: 'p', text: 'Osmanlı Devleti I. Dünya Savaşı’na Almanya’nın yanında girdi. Kafkas, Kanal, Irak, Hicaz-Yemen, Suriye-Filistin, Çanakkale, Galiçya-Makedonya-Romanya olmak üzere birçok cephede savaştı. Savaşın sonunda İttifak Devletleri yenildi ve Osmanlı Devleti ateşkes istemek zorunda kaldı.' },
            {
              id: 'b2', type: 'table',
              caption: 'I. Dünya Savaşı’nda Osmanlı cepheleri',
              headers: ['Cephe', 'Karşı taraf', 'Sonuç'],
              rows: [
                ['Kafkas', 'Rusya', 'Sarıkamış faciası; ağır kayıp'],
                ['Kanal', 'İngiltere', 'Başarısız; Mısır alınamadı'],
                ['Çanakkale', 'İtilaf Devletleri', 'Kesin zafer; “Çanakkale geçilmez”'],
                ['Irak', 'İngiltere', 'Kut’ül Amare zaferi, sonra kayıp'],
                ['Suriye-Filistin', 'İngiltere', 'Son savunma hattı; Mustafa Kemal Yıldırım Orduları Komutanı'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Mondros’un en tehlikeli maddesi',
              text: '7. madde: “İtilaf Devletleri güvenliklerini tehdit edecek bir durumda herhangi bir stratejik noktayı işgal edebilecektir.” Bu madde, Anadolu’nun işgali için hukuki kılıf oluşturdu. 24. madde ise altı doğu ilinde karışıklık çıkarsa buraların işgal edilebileceğini öngörüyordu.',
            },
            { id: 'b4', type: 'h3', text: 'Cemiyetler' },
            {
              id: 'b5', type: 'table',
              headers: ['Millî varlığa yararlı', 'Millî varlığa zararlı'],
              rows: [
                ['Trakya-Paşaeli Cemiyeti', 'Mavri Mira'],
                ['İzmir Müdafaa-i Hukuk-ı Osmaniye', 'Etnik-i Eterya'],
                ['Doğu Anadolu Müdafaa-i Hukuk', 'Pontus Rum Cemiyeti'],
                ['Kilikyalılar Cemiyeti', 'Hınçak ve Taşnak'],
                ['Millî Kongre Cemiyeti', 'Sulh ve Selamet-i Osmaniye'],
                ['Anadolu Kadınları Müdafaa-i Vatan', 'İngiliz Muhipleri Cemiyeti'],
              ],
            },
            {
              id: 'b6', type: 'callout', variant: 'bilgi', title: 'Kuvâ-yı Milliye',
              text: 'İşgallere karşı halkın kendiliğinden oluşturduğu silahlı direniş güçleridir. Düzenli ordu kuruluncaya kadar işgalleri yavaşlatmış, millî bilinci canlı tutmuştur. Ancak düzenli bir komuta zinciri olmadığı için 1920’de düzenli orduya dönüştürülmüştür.',
            },
          ],
        },
        {
          id: 'ink-u1-p3', kind: 'content',
          title: 'Genelgeler ve Kongreler',
          subtitle: 'Millî mücadelenin yol haritası',
          blocks: [
            {
              id: 'b1', type: 'timeline',
              items: [
                { date: '19 Mayıs 1919', text: 'Mustafa Kemal Samsun’a çıktı. Millî Mücadele fiilen başladı.' },
                { date: '28 Mayıs 1919', text: 'Havza Genelgesi: İşgalleri protesto mitingleri düzenlenmesi istendi.' },
                { date: '22 Haziran 1919', text: 'Amasya Genelgesi: Millî Mücadele’nin ilk yazılı belgesi.' },
                { date: '23 Temmuz 1919', text: 'Erzurum Kongresi: Bölgesel toplanış, millî kararlar.' },
                { date: '4 Eylül 1919', text: 'Sivas Kongresi: Tüm yurdu temsil eden millî kongre.' },
                { date: '27 Aralık 1919', text: 'Temsil Heyeti Ankara’ya geldi.' },
                { date: '28 Ocak 1920', text: 'Misak-ı Millî kabul edildi.' },
                { date: '16 Mart 1920', text: 'İstanbul resmen işgal edildi, Meclis-i Mebusan kapatıldı.' },
              ],
            },
            {
              id: 'b2', type: 'callout', variant: 'tanim', title: 'Amasya Genelgesi’nin dört maddesi',
              text: '1) Vatanın bütünlüğü, milletin istiklali tehlikededir.\n2) İstanbul Hükûmeti üzerine aldığı sorumluluğu yerine getirememektedir.\n3) Milletin istiklalini yine milletin azim ve kararı kurtaracaktır.\n4) Milletin durumunu görüşmek üzere Sivas’ta millî bir kongre toplanacaktır.',
            },
            {
              id: 'b3', type: 'table',
              caption: 'İki kongrenin karşılaştırılması',
              headers: ['', 'Erzurum Kongresi', 'Sivas Kongresi'],
              rows: [
                ['Tarih', '23 Temmuz – 7 Ağustos 1919', '4 – 11 Eylül 1919'],
                ['Toplanış', 'Bölgesel', 'Millî'],
                ['Kararlar', 'Millî', 'Millî'],
                ['Manda-himaye', 'Reddedildi', 'Kesin olarak reddedildi'],
                ['Cemiyetler', 'Doğu illeri cemiyetleri birleşti', 'Tüm cemiyetler “Anadolu ve Rumeli Müdafaa-i Hukuk Cemiyeti” adıyla birleşti'],
              ],
            },
            {
              id: 'b4', type: 'callout', variant: 'ipucu', title: 'Misak-ı Millî’yi hatırlama',
              text: 'Misak-ı Millî, Kurtuluş Savaşı’nın siyasi programıdır. Özü şudur: Mondros imzalandığı andaki sınırlar içinde kalan Türk vatanı bölünemez bir bütündür; kapitülasyonlar kaldırılacak, azınlık hakları komşu ülkelerdeki Müslümanlarla eşit olacaktır.',
            },
          ],
        },
        {
          id: 'ink-u1-q', kind: 'quiz',
          title: '1. Ünite Değerlendirme Testi',
          subtitle: 'Bir Kahraman Doğuyor ve Millî Uyanış',
          questionIds: ['ink-001', 'ink-002', 'ink-003', 'ink-004', 'ink-005', 'ink-006', 'ink-007', 'ink-008', 'ink-009'],
        },
      ],
    },
    {
      id: 'ink-u2',
      title: '2. Ünite — Millî Bir Destan: Ya İstiklal Ya Ölüm',
      pages: [
        {
          id: 'ink-u2-p1', kind: 'content',
          title: 'TBMM’nin Açılması',
          subtitle: 'Yeni bir devletin doğuşu',
          blocks: [
            { id: 'b1', type: 'p', text: 'İstanbul’un işgal edilmesi ve Meclis-i Mebusan’ın kapatılması üzerine Mustafa Kemal, Ankara’da olağanüstü yetkilere sahip bir meclisin toplanması için çağrı yaptı. 23 Nisan 1920’de TBMM açıldı ve “Egemenlik kayıtsız şartsız milletindir.” ilkesi benimsendi.' },
            {
              id: 'b2', type: 'list',
              items: [
                'Meclisin üstünde bir güç yoktur (güçler birliği ilkesi).',
                'Yasama, yürütme ve yargı yetkileri TBMM’de toplanmıştır.',
                'Hükûmet kurmak zorunludur; geçici bir hükûmet başkanı tanınmaz.',
                'Padişah ve halife, meclisin düzenleyeceği esaslar içinde yerini alacaktır.',
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Ayaklanmalar',
              text: 'TBMM’ye karşı Anzavur, Kuvâ-yı İnzibatiye (Halifelik Ordusu), Çapanoğlu ve Delibaş gibi birçok ayaklanma çıktı. TBMM bunlara karşı Hıyanet-i Vataniye Kanunu’nu çıkardı ve İstiklal Mahkemelerini kurdu.',
            },
            {
              id: 'b4', type: 'callout', variant: 'bilgi', title: 'Sevr Antlaşması (10 Ağustos 1920)',
              text: 'Osmanlı Devleti’ni fiilen ortadan kaldıran bu antlaşma TBMM tarafından tanınmamıştır. Mebusan Meclisi kapatıldığı için onaylanamamış, bu yüzden hukuken hiç yürürlüğe girmemiştir. Sevr, Türk milletinin direniş azmini artırmıştır.',
            },
          ],
        },
        {
          id: 'ink-u2-p2', kind: 'content',
          title: 'Kurtuluş Savaşı Cepheleri',
          subtitle: 'Doğu, Güney ve Batı',
          blocks: [
            {
              id: 'b1', type: 'table',
              caption: 'Üç cephe',
              headers: ['Cephe', 'Kime karşı', 'Komutan', 'Sonuç'],
              rows: [
                ['Doğu', 'Ermeniler', 'Kâzım Karabekir', 'Gümrü Antlaşması (3 Aralık 1920)'],
                ['Güney', 'Fransızlar', 'Kuvâ-yı Milliye (halk direnişi)', 'Ankara Antlaşması (20 Ekim 1921)'],
                ['Batı', 'Yunanlılar', 'İsmet Paşa, Mustafa Kemal', 'Mudanya Ateşkesi (11 Ekim 1922)'],
              ],
            },
            {
              id: 'b2', type: 'timeline',
              items: [
                { date: '6-10 Ocak 1921', text: 'I. İnönü Zaferi — Düzenli ordunun ilk başarısı, Londra Konferansı’na davet.' },
                { date: '23 Mart – 1 Nisan 1921', text: 'II. İnönü Zaferi — İtalyanlar Anadolu’yu boşaltmaya başladı.' },
                { date: 'Temmuz 1921', text: 'Kütahya-Eskişehir Savaşları — Ordu Sakarya’nın doğusuna çekildi.' },
                { date: '23 Ağustos – 13 Eylül 1921', text: 'Sakarya Meydan Muharebesi — Savunma savaşı, kesin zafer.' },
                { date: '26 Ağustos – 9 Eylül 1922', text: 'Büyük Taarruz — 9 Eylül’de İzmir’e girildi.' },
                { date: '11 Ekim 1922', text: 'Mudanya Ateşkes Antlaşması.' },
                { date: '24 Temmuz 1923', text: 'Lozan Barış Antlaşması.' },
              ],
            },
            {
              id: 'b3', type: 'quote',
              text: 'Hattı müdafaa yoktur, sathı müdafaa vardır. O satıh bütün vatandır. Vatanın her karış toprağı vatandaşın kanıyla ıslanmadıkça terk olunamaz.',
              source: 'Mustafa Kemal, Sakarya – 1921',
            },
            {
              id: 'b4', type: 'callout', variant: 'ipucu', title: 'Tekâlif-i Milliye Emirleri',
              text: 'Sakarya öncesinde ordunun ihtiyaçlarını karşılamak için yayımlanan on emirdir: Her aileden bir kat çamaşır, çorap ve çarık; elde bulunan yiyecek ve giyeceğin %40’ı; taşıtların %20’si… Millî seferberliğin en somut örneğidir.',
            },
          ],
        },
        {
          id: 'ink-u2-p3', kind: 'content',
          title: 'Lozan Barış Antlaşması',
          subtitle: 'Bağımsızlığın tescili',
          blocks: [
            { id: 'b1', type: 'p', text: '24 Temmuz 1923’te imzalanan Lozan Antlaşması, yeni Türk devletinin bağımsızlığını dünyaya kabul ettiren belgedir. Görüşmelerde Türk heyetine İsmet Paşa başkanlık etmiştir. Antlaşma, Sevr’i tarihe gömmüş ve Misak-ı Millî’nin büyük bölümünü gerçekleştirmiştir.' },
            {
              id: 'b2', type: 'table',
              caption: 'Lozan’da alınan başlıca kararlar',
              headers: ['Konu', 'Karar'],
              rows: [
                ['Kapitülasyonlar', 'Tamamen kaldırıldı'],
                ['Sınırlar', 'Suriye, Irak ve Batı sınırı büyük ölçüde belirlendi'],
                ['Musul', 'Çözülemedi; İngiltere ile görüşmeye bırakıldı'],
                ['Boğazlar', 'Uluslararası komisyona bırakıldı (1936’da düzeltildi)'],
                ['Azınlıklar', 'Türk vatandaşı sayıldı; ayrıcalıklar kaldırıldı'],
                ['Nüfus mübadelesi', 'İstanbul Rumları ve Batı Trakya Türkleri hariç mübadele'],
                ['Osmanlı borçları', 'Türkiye’ye düşen pay taksitle ödenecek'],
                ['Patrikhane', 'İstanbul’da kalacak, siyasi yetkisi olmayacak'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Neden kesin zafer?',
              text: 'Lozan yalnızca bir savaşın bitişi değil, yeni bir devletin uluslararası tanınmasıdır. Kapitülasyonların kaldırılması ekonomik bağımsızlığı, sınırların çizilmesi siyasi bağımsızlığı, azınlık ayrıcalıklarının bitmesi hukuki bağımsızlığı sağlamıştır.',
            },
          ],
        },
        {
          id: 'ink-u2-q', kind: 'quiz',
          title: '2. Ünite Değerlendirme Testi',
          subtitle: 'Millî Bir Destan',
          questionIds: ['ink-010', 'ink-011', 'ink-012', 'ink-013', 'ink-024', 'ink-014'],
        },
      ],
    },
    {
      id: 'ink-u3',
      title: '3. Ünite — Atatürkçülük ve Çağdaşlaşan Türkiye',
      pages: [
        {
          id: 'ink-u3-p1', kind: 'content',
          title: 'İnkılaplar',
          subtitle: 'Siyasi, hukuki, eğitim ve toplumsal alanda',
          blocks: [
            {
              id: 'b1', type: 'table',
              caption: 'Alanlarına göre inkılaplar',
              headers: ['Alan', 'İnkılap', 'Tarih'],
              rows: [
                ['Siyasi', 'Saltanatın kaldırılması', '1 Kasım 1922'],
                ['Siyasi', 'Cumhuriyetin ilanı', '29 Ekim 1923'],
                ['Siyasi', 'Halifeliğin kaldırılması', '3 Mart 1924'],
                ['Hukuk', 'Türk Medeni Kanunu’nun kabulü', '17 Şubat 1926'],
                ['Eğitim', 'Tevhid-i Tedrisat Kanunu', '3 Mart 1924'],
                ['Eğitim', 'Yeni Türk harflerinin kabulü', '1 Kasım 1928'],
                ['Eğitim', 'Millet Mektepleri’nin açılması', '1928'],
                ['Toplum', 'Şapka Kanunu', '25 Kasım 1925'],
                ['Toplum', 'Tekke ve zaviyelerin kapatılması', '30 Kasım 1925'],
                ['Toplum', 'Takvim, saat, ölçü değişikliği', '1925-1931'],
                ['Toplum', 'Soyadı Kanunu', '21 Haziran 1934'],
                ['Ekonomi', 'Aşar vergisinin kaldırılması', '17 Şubat 1925'],
                ['Ekonomi', 'Teşvik-i Sanayi Kanunu', '1927'],
                ['Ekonomi', 'I. Beş Yıllık Sanayi Planı', '1934'],
              ],
            },
            {
              id: 'b2', type: 'callout', variant: 'bilgi', title: 'Tevhid-i Tedrisat neden önemli?',
              text: 'Öğretimin birleştirilmesi, medrese-mektep ikiliğini sona erdirdi. Tüm eğitim kurumları Maarif Vekâleti’ne bağlandı. Böylece hem eğitim birliği hem de laik eğitim yolunda temel adım atılmış oldu.',
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Medeni Kanun ve kadın hakları',
              text: 'Türk Medeni Kanunu ile tek eşlilik zorunlu hâle geldi, resmî nikâh şartı getirildi, kadın-erkek mirasta eşitlendi, kadınlara boşanma ve mahkemede şahitlik hakkı tanındı, meslek seçme özgürlüğü sağlandı.',
            },
          ],
        },
        {
          id: 'ink-u3-p2', kind: 'content',
          title: 'Atatürk İlkeleri',
          subtitle: 'Altı temel ilke ve bütünleyici ilkeler',
          blocks: [
            {
              id: 'b1', type: 'terms',
              items: [
                { term: 'Cumhuriyetçilik', def: 'Egemenliğin millete ait olması, yöneticilerin seçimle belirlenmesi. İlgili inkılaplar: Cumhuriyetin ilanı, siyasi partilerin kurulması, kadınlara seçme-seçilme hakkı.' },
                { term: 'Milliyetçilik', def: 'Türk milletini sevmek, birlik ve beraberliği korumak. Irkçılık değildir. İlgili: TDK, TTK, Misak-ı Millî.' },
                { term: 'Halkçılık', def: 'Kanun önünde eşitlik, ayrıcalıksız ve sınıfsız toplum. İlgili: Aşarın kaldırılması, Medeni Kanun, Soyadı Kanunu.' },
                { term: 'Devletçilik', def: 'Özel sektörün yetersiz kaldığı alanlarda devletin ekonomiye girmesi. İlgili: Sümerbank, Etibank, Beş Yıllık Planlar.' },
                { term: 'Laiklik', def: 'Din ve devlet işlerinin ayrılması, inanç özgürlüğünün güvence altına alınması. İlgili: Halifeliğin kaldırılması, Tevhid-i Tedrisat, Medeni Kanun.' },
                { term: 'İnkılapçılık', def: 'Çağın gereklerine göre sürekli yenilenme. Diğer beş ilkenin devamlılığını sağlayan ilkedir.' },
              ],
            },
            {
              id: 'b2', type: 'list',
              items: [
                'Bütünleyici ilkeler: Millî egemenlik, millî birlik ve beraberlik, yurtta sulh cihanda sulh, çağdaşlaşma, bilimsellik ve akılcılık, insan ve insanlık sevgisi, millî bağımsızlık.',
                'İlkeler ilk kez 1931’de CHP programında yer aldı, 1937’de Anayasa’ya girdi.',
                'İlkeler birbirinden bağımsız değildir; her biri diğerini destekler ve tamamlar.',
              ],
            },
            {
              id: 'b3', type: 'quote',
              text: 'Hayatta en hakiki mürşit ilimdir.',
              source: 'Mustafa Kemal Atatürk',
            },
          ],
        },
        {
          id: 'ink-u3-p3', kind: 'content',
          title: 'Dış Politika ve Atatürk’ün Ölümü',
          subtitle: 'Yurtta sulh, cihanda sulh',
          blocks: [
            {
              id: 'b1', type: 'timeline',
              items: [
                { date: '1926', text: 'Ankara Antlaşması — Musul Irak’a bırakıldı.' },
                { date: '1932', text: 'Türkiye Milletler Cemiyeti’ne üye oldu.' },
                { date: '1934', text: 'Balkan Antantı — Türkiye, Yunanistan, Yugoslavya, Romanya.' },
                { date: '1936', text: 'Montrö Boğazlar Sözleşmesi — Boğazlarda tam egemenlik.' },
                { date: '1937', text: 'Sadabat Paktı — Türkiye, İran, Irak, Afganistan.' },
                { date: '1938', text: 'Hatay Devleti kuruldu; Atatürk 10 Kasım’da vefat etti.' },
                { date: '1939', text: 'Hatay anavatana katıldı.' },
              ],
            },
            {
              id: 'b2', type: 'callout', variant: 'bilgi', title: 'Montrö’nün önemi',
              text: 'Lozan’da Boğazlar uluslararası bir komisyona bırakılmış ve askerden arındırılmıştı. 1936 Montrö Sözleşmesi ile komisyon kaldırıldı, Boğazlarda asker bulundurma hakkı geri alındı. Bu, Lozan’ın eksik kalan yönünün barışçı yoldan tamamlanmasıdır.',
            },
            { id: 'b3', type: 'p', text: 'Atatürk 10 Kasım 1938’de Dolmabahçe Sarayı’nda vefat etti. Naaşı 21 Kasım 1938’de Etnografya Müzesi’ne, 10 Kasım 1953’te ise Anıtkabir’e nakledildi. Ölümünün ardından İsmet İnönü cumhurbaşkanı seçildi.' },
            {
              id: 'b4', type: 'quote',
              text: 'Benim naçiz vücudum elbet bir gün toprak olacaktır; fakat Türkiye Cumhuriyeti ilelebet payidar kalacaktır.',
              source: 'Mustafa Kemal Atatürk',
            },
          ],
        },
        {
          id: 'ink-u3-q', kind: 'quiz',
          title: '3. Ünite Değerlendirme Testi',
          subtitle: 'Atatürkçülük ve Çağdaşlaşan Türkiye',
          questionIds: ['ink-015', 'ink-016', 'ink-017', 'ink-018', 'ink-019', 'ink-020', 'ink-021', 'ink-022', 'ink-023'],
        },
      ],
    },
  ],
}
