import type { Book, Question } from '../types'

export const questions: Question[] = [
  {
    id: 'tur-001', subjectId: 'turkce', topic: 'Sözcükte Anlam', difficulty: 1,
    stem: '“Gözlerindeki ışık, bütün odayı aydınlattı.” cümlesindeki “ışık” sözcüğünün kullanımı aşağıdakilerden hangisiyle aynıdır?',
    options: [
      'Sokak lambasının ışığı camdan içeri süzülüyordu.',
      'Bu çocuk ailesinin tek ışığı, tek umudu.',
      'Işık hızı saniyede yaklaşık 300.000 km’dir.',
      'Odanın ışığını açar mısın?',
    ],
    answer: 1,
    explanation: 'Öncül cümlede “ışık” gerçek anlamda değil, “sevinç, canlılık” anlamında mecaz olarak kullanılmıştır. B seçeneğinde de “umut” anlamıyla mecazdır. Diğerlerinde gerçek anlamdadır.',
  },
  {
    id: 'tur-002', subjectId: 'turkce', topic: 'Sözcükte Anlam', difficulty: 2,
    stem: 'Aşağıdaki cümlelerin hangisinde altı çizili sözcük terim anlamıyla kullanılmıştır?',
    options: [
      'Yolun <u>kenarında</u> kır çiçekleri açmıştı.',
      'Üçgenin <u>kenar</u> uzunlukları toplamına çevre denir.',
      'Toplantıda hep <u>kenarda</u> durdu.',
      'Masanın <u>kenarına</u> dikkat et, çarpacaksın.',
    ],
    answer: 1,
    explanation: 'Terim, bir bilim veya sanat dalına ait özel anlamdır. “Kenar” B’de geometri terimidir; diğerlerinde günlük gerçek anlamıyla kullanılmıştır.',
  },
  {
    id: 'tur-003', subjectId: 'turkce', topic: 'Sözcükte Anlam', difficulty: 2,
    stem: '“Ağır” sözcüğü aşağıdakilerin hangisinde “anlaşılması güç” anlamında kullanılmıştır?',
    options: [
      'Bu çanta benim için çok ağır.',
      'Ağır bir dille yazılmış, iki sayfada bıraktım.',
      'Hastanın durumu ağırmış.',
      'Ağır ağır yürüyerek kapıya yöneldi.',
    ],
    answer: 1,
    explanation: 'B’de “ağır dil” anlaşılması zor, yoğun dil demektir. A’da kütle, C’de ciddi, D’de yavaş anlamındadır.',
  },
  {
    id: 'tur-004', subjectId: 'turkce', topic: 'Deyim ve Atasözü', difficulty: 1,
    stem: '“Damlaya damlaya göl olur.” atasözüyle anlamca en yakın olan aşağıdakilerden hangisidir?',
    options: [
      'Az veren candan, çok veren maldan.',
      'Sakla samanı, gelir zamanı.',
      'Küçük küçük biriktirilen şeyler zamanla büyür.',
      'Ayağını yorganına göre uzat.',
    ],
    answer: 2,
    explanation: 'Atasözü, küçük birikimlerin zamanla büyük bir değere dönüşeceğini anlatır. C seçeneği bu yargının doğrudan karşılığıdır.',
  },
  {
    id: 'tur-005', subjectId: 'turkce', topic: 'Deyim ve Atasözü', difficulty: 2,
    stem: 'Aşağıdaki cümlelerin hangisinde deyim, anlamına uygun kullanılmamıştır?',
    options: [
      'Sınav sonucunu duyunca etekleri zil çaldı.',
      'Çok çalıştı ama pes etmedi, dişini sıktı.',
      'Ona güvenmiştim, tam anlamıyla kulak misafiri oldu.',
      'Bu işin altından kalkabileceğine inanıyorum.',
    ],
    answer: 2,
    explanation: '“Kulak misafiri olmak”, istemeden duymak demektir; güven ihaneti anlamı taşımaz. Cümlede yanlış kullanılmıştır.',
  },
  {
    id: 'tur-006', subjectId: 'turkce', topic: 'Cümlede Anlam', difficulty: 2,
    stem: '“Otobüs bozulduğu için toplantıya geç kaldık.” cümlesinde aşağıdaki anlam ilişkilerinden hangisi vardır?',
    options: ['Amaç–sonuç', 'Neden–sonuç', 'Koşul–sonuç', 'Karşılaştırma'],
    answer: 1,
    explanation: '“-dığı için” neden bildirir. Geç kalmanın nedeni otobüsün bozulmasıdır; bu bir neden–sonuç ilişkisidir.',
  },
  {
    id: 'tur-007', subjectId: 'turkce', topic: 'Cümlede Anlam', difficulty: 2,
    stem: 'Aşağıdaki cümlelerin hangisi öznel bir yargı içerir?',
    options: [
      'Roman 384 sayfadan oluşuyor.',
      'Kitap 2019 yılında yayımlandı.',
      'Yazarın en etkileyici romanı budur.',
      'Eser on iki dile çevrildi.',
    ],
    answer: 2,
    explanation: 'Öznel yargılar kişiden kişiye değişir ve kanıtlanamaz. “En etkileyici” değerlendirmesi kişisel bir görüştür.',
  },
  {
    id: 'tur-008', subjectId: 'turkce', topic: 'Cümlede Anlam', difficulty: 3,
    stem: '“Ders çalışsaydı bu soruyu yapardı.” cümlesinden kesin olarak çıkarılabilecek yargı hangisidir?',
    options: [
      'Soru çok zordu.',
      'Ders çalışmamıştır ve soruyu yapamamıştır.',
      'Öğrenci sınavdan düşük almıştır.',
      'Öğretmen konuyu anlatmamıştır.',
    ],
    answer: 1,
    explanation: '“-saydı … -ardı” yapısı gerçekleşmemiş koşul bildirir. Buradan hem çalışmadığı hem de soruyu yapamadığı kesin olarak çıkar.',
  },
  {
    id: 'tur-009', subjectId: 'turkce', topic: 'Paragraf', difficulty: 2,
    passage: 'Okumak, başkalarının düşünceleriyle kendi düşüncemizi karşılaştırma imkânı verir. Bir kitabı bitirdiğimizde aslında yalnızca bilgi edinmiş olmayız; bakış açımızı da genişletmiş oluruz. Bu yüzden düzenli okuyan insanlar, karşılaştıkları sorunlara birden fazla açıdan yaklaşabilir.',
    stem: 'Bu parçanın ana düşüncesi aşağıdakilerden hangisidir?',
    options: [
      'Kitap okumak boş zamanı değerlendirmenin en iyi yoludur.',
      'Okumak, insanın bakış açısını genişleterek çok yönlü düşünmesini sağlar.',
      'Her insan günde en az bir saat okumalıdır.',
      'Bilgi edinmenin tek yolu kitap okumaktır.',
    ],
    answer: 1,
    explanation: 'Parçada okumanın bilgiyle sınırlı kalmayıp bakış açısı kazandırdığı ve çok yönlü düşünmeyi sağladığı vurgulanır.',
  },
  {
    id: 'tur-010', subjectId: 'turkce', topic: 'Paragraf', difficulty: 3,
    passage: '(I) Arılar, kovana döndüklerinde özel bir dans sergiler. (II) Bu dansın açısı, besinin güneşe göre yönünü gösterir. (III) Bal, kahvaltıların vazgeçilmez lezzetidir. (IV) Dansın süresi ise besinin uzaklığı hakkında bilgi verir.',
    stem: 'Numaralanmış cümlelerden hangisi parçanın akışını bozmaktadır?',
    options: ['I', 'II', 'III', 'IV'],
    answer: 2,
    explanation: 'Parça arıların iletişim dansını anlatır. III. cümle balın lezzetinden söz ederek konu bütünlüğünü bozar.',
  },
  {
    id: 'tur-011', subjectId: 'turkce', topic: 'Paragraf', difficulty: 2,
    passage: 'Deniz suyu yükselmeye başladığında kıyıdaki kumsal önce daralır. Dalgalar kumu alıp açığa taşır. Yıllar içinde kıyı çizgisi geriler ve sahil evleri suyla burun buruna gelir.',
    stem: 'Bu parçanın anlatımında ağırlıklı olarak hangi anlatım biçimi kullanılmıştır?',
    options: ['Tartışma', 'Açıklama', 'Öyküleme', 'Betimleme'],
    answer: 1,
    explanation: 'Parça bir süreci bilgi verme amacıyla, tarafsız biçimde aktarmaktadır; bu açıklayıcı anlatımdır.',
  },
  {
    id: 'tur-012', subjectId: 'turkce', topic: 'Fiilimsiler', difficulty: 1,
    stem: 'Aşağıdaki cümlelerin hangisinde sıfat-fiil (ortaç) vardır?',
    options: [
      'Koşarak sınıfa girdi.',
      'Kırılan cam yerde duruyordu.',
      'Yüzmeyi çok severim.',
      'Eve gelince beni ara.',
    ],
    answer: 1,
    explanation: '“Kırılan”, “-an” sıfat-fiil ekiyle türemiş ve “cam” adını nitelemiştir. A ve D zarf-fiil, C isim-fiildir.',
  },
  {
    id: 'tur-013', subjectId: 'turkce', topic: 'Fiilimsiler', difficulty: 2,
    stem: '“Gülüşü herkesi rahatlatan bu çocuk, konuşurken gözlerini kaçırıyordu.” cümlesinde kaç fiilimsi vardır?',
    options: ['1', '2', '3', '4'],
    answer: 1,
    explanation: '“Rahatlatan” (sıfat-fiil) ve “konuşurken” (zarf-fiil) olmak üzere iki fiilimsi vardır. “Gülüşü”ndeki “-ş” burada kalıcı ada dönüşmüştür.',
  },
  {
    id: 'tur-014', subjectId: 'turkce', topic: 'Cümlenin Ögeleri', difficulty: 2,
    stem: '“Yağmurdan sonra bahçedeki güller daha canlı görünüyordu.” cümlesinin öznesi hangisidir?',
    options: ['Yağmurdan sonra', 'Bahçedeki güller', 'Daha canlı', 'Görünüyordu'],
    answer: 1,
    explanation: 'Yükleme “ne görünüyordu?” diye sorulduğunda “bahçedeki güller” cevabı gelir; bu, cümlenin öznesidir.',
  },
  {
    id: 'tur-015', subjectId: 'turkce', topic: 'Cümlenin Ögeleri', difficulty: 3,
    stem: 'Aşağıdaki cümlelerin hangisi “özne + belirtili nesne + yüklem” dizilişindedir?',
    options: [
      'Ali kitabı okudu.',
      'Ali kitap okudu.',
      'Kitap okundu.',
      'Ali okula gitti.',
    ],
    answer: 0,
    explanation: '“Kitabı” belirtme hâli ekiyle çekimlendiği için belirtili nesnedir. B’de belirtisiz nesne, C’de sözde özne, D’de dolaylı tümleç vardır.',
  },
  {
    id: 'tur-016', subjectId: 'turkce', topic: 'Fiilde Çatı', difficulty: 3,
    stem: '“Cam, rüzgârdan kırıldı.” cümlesinin çatı özelliği aşağıdakilerden hangisidir?',
    options: ['Etken – geçişli', 'Edilgen – geçişsiz', 'Dönüşlü – geçişsiz', 'İşteş – geçişli'],
    answer: 1,
    explanation: 'Eylemi yapan belli değildir, “cam” sözde öznedir; fiil “-ıl” ekiyle edilgen ve nesne almadığı için geçişsizdir.',
  },
  {
    id: 'tur-017', subjectId: 'turkce', topic: 'Cümle Çeşitleri', difficulty: 2,
    stem: '“Ne yazık ki treni kaçırdık.” cümlesi yapısına göre hangisidir?',
    options: ['Basit', 'Birleşik', 'Sıralı', 'Bağlı'],
    answer: 0,
    explanation: 'Cümlede tek yüklem vardır ve yan cümlecik yoktur; “ne yazık ki” bir ara sözdür. Bu nedenle cümle basittir.',
  },
  {
    id: 'tur-018', subjectId: 'turkce', topic: 'Yazım Kuralları', difficulty: 1,
    stem: 'Aşağıdaki cümlelerin hangisinde yazım yanlışı vardır?',
    options: [
      'Yarın Ankara’ya gideceğiz.',
      'Türkçe’yi doğru kullanmalıyız.',
      '2025’te mezun olacak.',
      'Ali’nin defteri masada kalmış.',
    ],
    answer: 1,
    explanation: 'Dil adlarına gelen çekim ekleri kesme işaretiyle ayrılmaz: “Türkçeyi” biçiminde yazılmalıdır.',
  },
  {
    id: 'tur-019', subjectId: 'turkce', topic: 'Yazım Kuralları', difficulty: 2,
    stem: 'Aşağıdakilerin hangisinde “de/da” yazımı doğrudur?',
    options: [
      'Sende mi böyle düşünüyorsun?',
      'Kalem çantamda da yok.',
      'Bende para kalmadı, sen de yok mu?',
      'Okulada gitmedi.',
    ],
    answer: 1,
    explanation: 'Bağlaç olan “da” ayrı yazılır; “çantamda” bulunma hâlidir, bitişik yazılır. B seçeneğinde her iki kullanım da doğrudur.',
  },
  {
    id: 'tur-020', subjectId: 'turkce', topic: 'Noktalama', difficulty: 2,
    stem: '“Kitabı okudum (  ) ancak sonunu beğenmedim (  )” cümlesinde parantezle gösterilen yerlere sırasıyla hangi noktalama işaretleri gelmelidir?',
    options: ['virgül – nokta', 'noktalı virgül – nokta', 'iki nokta – ünlem', 'virgül – üç nokta'],
    answer: 0,
    explanation: '“Ancak” bağlacından önce virgül kullanılır; cümle tamamlandığı için sonuna nokta konur.',
  },
  {
    id: 'tur-021', subjectId: 'turkce', topic: 'Anlatım Bozukluğu', difficulty: 2,
    stem: 'Aşağıdaki cümlelerin hangisinde gereksiz sözcük kullanımından kaynaklanan anlatım bozukluğu vardır?',
    options: [
      'Yukarıya doğru yükseldi.',
      'Kapıyı yavaşça araladı.',
      'Bütün gün ders çalıştı.',
      'Yağmur akşama kadar sürdü.',
    ],
    answer: 0,
    explanation: '“Yükselmek” zaten yukarı doğru hareket bildirir; “yukarıya doğru” gereksiz kullanılmıştır.',
  },
  {
    id: 'tur-022', subjectId: 'turkce', topic: 'Anlatım Bozukluğu', difficulty: 3,
    stem: '“Öğrencilere kitap dağıtıldı ve teşekkür ettiler.” cümlesindeki anlatım bozukluğunun nedeni nedir?',
    options: [
      'Nesne eksikliği',
      'Özne–yüklem uyumsuzluğu',
      'Tamlama yanlışlığı',
      'Özne eksikliği (ikinci yüklemin öznesi yok)',
    ],
    answer: 3,
    explanation: 'Birinci yüklem edilgendir ve öznesi “kitap”tır. “Teşekkür ettiler” yükleminin öznesi (öğrenciler) cümlede eksiktir.',
  },
  {
    id: 'tur-023', subjectId: 'turkce', topic: 'Söz Sanatları', difficulty: 2,
    stem: '“Ay, bulutların arasından bize göz kırptı.” dizesinde hangi söz sanatı vardır?',
    options: ['Benzetme', 'Kişileştirme', 'Abartma', 'Konuşturma'],
    answer: 1,
    explanation: 'İnsana özgü “göz kırpmak” eylemi aya yüklenmiştir; bu kişileştirmedir (teşhis).',
  },
  {
    id: 'tur-024', subjectId: 'turkce', topic: 'Söz Sanatları', difficulty: 2,
    stem: '“Onun sesi bülbül gibiydi.” cümlesinde hangi söz sanatı kullanılmıştır?',
    options: ['Kişileştirme', 'Abartma', 'Benzetme', 'Konuşturma'],
    answer: 2,
    explanation: 'Ses, güzelliği bakımından bülbüle benzetilmiştir; “gibi” benzetme edatıyla benzetme (teşbih) yapılmıştır.',
  },
  {
    id: 'tur-025', subjectId: 'turkce', topic: 'Paragraf', difficulty: 3,
    passage: 'Bir şehri tanımak için müzelerini gezmek yetmez. O şehrin pazarına gitmeli, esnafın sesini duymalı, akşamüstü sokaklarında amaçsızca yürümelisiniz. Bina cepheleri size tarih anlatır ama şehrin bugününü ancak insanları anlatır.',
    stem: 'Bu parçada asıl anlatılmak istenen nedir?',
    options: [
      'Müzeler şehirleri tanımak için yetersizdir.',
      'Bir şehri gerçekten tanımak, gündelik yaşamına karışmakla mümkündür.',
      'Şehirlerin mimarisi tarih hakkında bilgi verir.',
      'Pazar yerleri şehirlerin en canlı yerleridir.',
    ],
    answer: 1,
    explanation: 'Yazar, mimari ve müze gibi statik unsurların yanında asıl olarak şehrin gündelik hayatına katılmayı önerir.',
  },
  {
    id: 'tur-026', subjectId: 'turkce', topic: 'Sözcükte Anlam', difficulty: 3,
    stem: 'Aşağıdaki cümlelerin hangisinde “yan anlam” söz konusudur?',
    options: [
      'Şişenin ağzını kapattı.',
      'Ağzı çok laf yapıyor.',
      'Ağzını açıp da konuşmadı.',
      'Ağzında bir yara çıkmış.',
    ],
    answer: 0,
    explanation: 'Yan anlam, gerçek anlamla ilgisini koruyarak yeni bir varlığa aktarılan anlamdır. Şişenin “ağzı”, biçim benzerliğiyle oluşmuş yan anlamdır.',
  },
  {
    id: 'tur-027', subjectId: 'turkce', topic: 'Fiilimsiler', difficulty: 3,
    stem: 'Aşağıdaki cümlelerin hangisinde fiilimsi yoktur?',
    options: [
      'Yürüyerek gelmeyi tercih etti.',
      'Okunacak kitaplar rafta duruyor.',
      'Dün akşam erkenden uyudu.',
      'Gülen yüzler hep hatırlanır.',
    ],
    answer: 2,
    explanation: 'C seçeneğindeki tek çekimli fiil “uyudu”dur; fiilimsi yoktur. Diğerlerinde isim-fiil, zarf-fiil ve sıfat-fiil bulunur.',
  },
  {
    id: 'tur-028', subjectId: 'turkce', topic: 'Cümlede Anlam', difficulty: 2,
    stem: '“Bu kitabı okumak istiyorsan önce şu üniteyi bitirmelisin.” cümlesinde hangi anlam ilişkisi vardır?',
    options: ['Koşul–sonuç', 'Neden–sonuç', 'Amaç–sonuç', 'Karşılaştırma'],
    answer: 0,
    explanation: 'Kitabı okuma isteği, üniteyi bitirme şartına bağlanmıştır; bu bir koşul (şart) cümlesidir.',
  },
]

export const book: Book = {
  id: 'turkce-8',
  subjectId: 'turkce',
  title: 'Türkçe 8 — Anlamın İzinde',
  subtitle: 'LGS Konu Anlatımı ve Uygulama Kitabı',
  author: 'Ali Kerem Yayınları Türkçe Kurulu',
  edition: '1. Baskı',
  year: 2026,
  blurb:
    'Sözcüğün en küçük anlam katmanından paragrafın bütününe uzanan bir yolculuk. Her konu, LGS’de karşınıza çıkan soru tipleriyle eşleştirilerek anlatıldı.',
  chapters: [
    {
      id: 'tur-u1',
      title: '1. Ünite — Sözcükte ve Cümlede Anlam',
      pages: [
        {
          id: 'tur-u1-p1', kind: 'content',
          title: 'Sözcükte Anlam',
          subtitle: 'Bir kelimenin kaç yüzü vardır?',
          blocks: [
            { id: 'b1', type: 'p', text: 'Türkçede bir sözcük tek bir anlamla sınırlı değildir. Aynı kelime, içinde bulunduğu cümleye göre bambaşka bir anlam kazanabilir. LGS’de “sözcükte anlam” sorularının tamamı bu esnekliği ölçer: Size bir cümle verilir ve o cümledeki sözcüğün hangi anlam katmanında kullanıldığı sorulur.' },
            { id: 'b2', type: 'h3', text: 'Temel (Gerçek) Anlam' },
            { id: 'b3', type: 'p', text: 'Bir sözcüğü duyduğumuzda zihnimizde beliren ilk, en yalın görüntüdür. Sözlükteki ilk madde başıdır. “Göz” dediğimizde aklımıza gelen görme organı, temel anlamdır.' },
            { id: 'b4', type: 'h3', text: 'Yan Anlam' },
            { id: 'b5', type: 'p', text: 'Sözcüğün temel anlamıyla bağını koparmadan, çoğunlukla biçim ya da işlev benzerliğiyle başka bir varlığa aktarılmasıdır. “İğnenin gözü”, “masanın ayağı”, “şişenin ağzı” örneklerinde benzerlik ilişkisi hâlâ görülebilir.' },
            { id: 'b6', type: 'h3', text: 'Mecaz Anlam' },
            { id: 'b7', type: 'p', text: 'Sözcüğün gerçek anlamından tamamen uzaklaşarak bambaşka bir kavramı karşılamasıdır. “Bu çocuk ailesinin ışığı.” cümlesinde ışık, aydınlatan bir kaynak değil; umut demektir.' },
            { id: 'b8', type: 'h3', text: 'Terim Anlam' },
            { id: 'b9', type: 'p', text: 'Bir bilim, sanat ya da meslek dalına ait özel anlamdır. “Kenar” günlük dilde kıyı demekken geometride üçgeni oluşturan doğru parçasıdır.' },
            {
              id: 'b10', type: 'table',
              caption: 'Tek sözcük, dört farklı anlam katmanı',
              headers: ['Anlam', 'Örnek cümle', 'Açıklama'],
              rows: [
                ['Temel', 'Gözlerim yoruldu.', 'Görme organı'],
                ['Yan', 'İğnenin gözünden ip geçiremedim.', 'Biçim benzerliği'],
                ['Mecaz', 'Bu işte bir göz var.', 'Kontrol, gözetim'],
                ['Terim', 'Pencerenin gözleri kırılmış.', 'Mimarlık terimi'],
              ],
            },
            {
              id: 'b11', type: 'callout', variant: 'ipucu', title: 'Sınav taktiği',
              text: 'Önce sözcüğün sözlükteki ilk anlamını düşünün. Cümlede o anlam kullanılmıyorsa, benzerlik ilişkisi hâlâ kurulabiliyor mu diye bakın. Kurulabiliyorsa yan anlam, kurulamıyorsa mecaz anlamdır.',
            },
            {
              id: 'b12', type: 'example', title: 'Örnek',
              question: '“Tartışma sırasında herkes ağır sözler söyledi.” cümlesindeki “ağır” sözcüğü hangi anlamdadır?',
              solution: [
                'Sözcüğün temel anlamı “kütlesi çok olan”dır; burada bu anlam yok.',
                'Sözlerin kütlesi olamayacağı için benzerlik ilişkisi de kurulamaz.',
                'Öyleyse sözcük gerçek anlamından tamamen uzaklaşmıştır: kırıcı, incitici anlamında mecazdır.',
              ],
            },
          ],
        },
        {
          id: 'tur-u1-p2', kind: 'content',
          title: 'Deyimler, Atasözleri ve İkilemeler',
          subtitle: 'Kalıplaşmış sözlerin dünyası',
          blocks: [
            { id: 'b1', type: 'p', text: 'Türkçenin anlatım gücünü büyük ölçüde kalıplaşmış sözler oluşturur. Bu sözlerin ortak özelliği, sözcükleri değiştirilemez ve çoğunlukla mecaz anlam taşımalarıdır.' },
            {
              id: 'b2', type: 'terms',
              items: [
                { term: 'Deyim', def: 'En az iki sözcükten oluşan, genellikle mecaz anlamlı, kalıplaşmış söz. Yargı bildirmez: “etekleri zil çalmak”, “pabucu dama atılmak”.' },
                { term: 'Atasözü', def: 'Toplumun ortak deneyimini yargı hâlinde aktaran, kalıplaşmış söz: “Ağaç yaşken eğilir.”' },
                { term: 'İkileme', def: 'Anlamı güçlendirmek için sözcüğün yinelenmesi ya da yakın/karşıt sözcüklerin yan yana gelmesi: “yavaş yavaş”, “irili ufaklı”, “eğri büğrü”.' },
                { term: 'Özdeyiş (vecize)', def: 'Söyleyeni belli olan, kısa ve etkileyici söz: “Hayatta en hakiki mürşit ilimdir.”' },
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Deyim mi, atasözü mü?',
              text: 'Ölçüt basittir: Söz bir öğüt ya da genel kural veriyorsa atasözüdür. Yalnızca bir durumu resmediyorsa deyimdir. “Damlaya damlaya göl olur.” bir kural verir → atasözü. “Göz atmak” yalnızca eylemi anlatır → deyim.',
            },
            { id: 'b4', type: 'h3', text: 'Sık Karıştırılan Deyimler' },
            {
              id: 'b5', type: 'table',
              headers: ['Deyim', 'Anlamı'],
              rows: [
                ['Kulak misafiri olmak', 'İstemeden, rastlantıyla duymak'],
                ['Kulak kabartmak', 'Bilerek dinlemeye çalışmak'],
                ['Göz yummak', 'Görmezden gelmek, hoş görmek'],
                ['Gözden düşmek', 'Değerini, itibarını yitirmek'],
                ['Eli ağır olmak', 'Yavaş çalışmak'],
                ['Eli açık olmak', 'Cömert olmak'],
              ],
            },
            {
              id: 'b6', type: 'example', title: 'Örnek',
              question: '“Sınavdan geçtiğini duyunca ……… .” cümlesini hangi deyim tamamlar?',
              solution: [
                'Cümlede büyük bir sevinç anlatılıyor.',
                '“Etekleri zil çalmak” deyimi aşırı sevinmeyi ifade eder.',
                'Doğru tamamlama: “Sınavdan geçtiğini duyunca etekleri zil çaldı.”',
              ],
            },
            {
              id: 'b7', type: 'quote',
              text: 'Söz ola kese savaşı, söz ola kestire başı.',
              source: 'Yunus Emre',
            },
          ],
        },
        {
          id: 'tur-u1-p3', kind: 'content',
          title: 'Cümlede Anlam İlişkileri',
          subtitle: 'Neden, amaç, koşul ve ötesi',
          blocks: [
            { id: 'b1', type: 'p', text: 'Cümlede anlam soruları, iki yargı arasındaki mantıksal bağı doğru okumanızı ister. Bu bağı kuran çoğunlukla bir ek ya da bağlaçtır. Aşağıdaki tabloyu ezberlemek yerine, her ilişkiyi kendi cümlenizle örneklendirerek çalışın.' },
            {
              id: 'b2', type: 'table',
              caption: 'Anlam ilişkileri ve ipucu sözcükleri',
              headers: ['İlişki', 'İpucu', 'Örnek'],
              rows: [
                ['Neden–sonuç', '-dığı için, -den, diye, çünkü', 'Yağmur yağdığı için maç ertelendi.'],
                ['Amaç–sonuç', '-mek için, -sın diye, üzere', 'Sınavı kazanmak için gece gündüz çalıştı.'],
                ['Koşul–sonuç', '-sa/-se, -ınca, mi, ancak … ise', 'Erken kalkarsan otobüse yetişirsin.'],
                ['Karşılaştırma', 'daha, en, kadar, göre', 'Bu roman diğerinden daha akıcı.'],
                ['Karşıtlık', 'ama, fakat, oysa, ne var ki', 'Çok çalıştı ama sonuç alamadı.'],
                ['Eşitlik', 'hem … hem, gibi, kadar', 'Kardeşi kadar çalışkandır.'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Neden mi, amaç mı?',
              text: 'Amaç–sonuç cümlelerinde istek, niyet vardır ve sonuç gerçekleşmemiş olabilir. Neden–sonuç cümlelerinde ise sonuç zaten gerçekleşmiştir. “Dinlenmek için oturdu” (amaç) ile “Yorulduğu için oturdu” (neden) arasındaki fark budur.',
            },
            { id: 'b4', type: 'h3', text: 'Öznel ve Nesnel Yargılar' },
            {
              id: 'b5', type: 'list',
              items: [
                'Nesnel yargı: Doğruluğu kişiden kişiye değişmez, kanıtlanabilir. “Roman 384 sayfadır.”',
                'Öznel yargı: Kişisel görüş içerir, kanıtlanamaz. “Roman çok sürükleyicidir.”',
                'Bir cümlede hem nesnel hem öznel bölüm bulunabilir: “384 sayfalık bu roman çok akıcıdır.”',
              ],
            },
            { id: 'b6', type: 'h3', text: 'Diğer Sık Sorulan Anlamlar' },
            {
              id: 'b7', type: 'list',
              items: [
                'Varsayım: “Diyelim ki”, “tut ki”, “farz edelim” kalıplarıyla kurulur.',
                'Tahmin: “Herhâlde”, “sanırım”, “galiba”, “-malı/-meli” kesin olmayan yargı bildirir.',
                'Öneri: “-meli/-malı”, “-sa iyi olur”, “bence” kalıplarıyla yol gösterilir.',
                'Eleştiri: Bir yönün olumsuz değerlendirilmesidir.',
                'Özeleştiri: Kişinin kendi eksiğini kabul etmesidir.',
              ],
            },
            {
              id: 'b8', type: 'example', title: 'Örnek',
              question: '“Kitabı bitirdim ama sonunu hiç beğenmedim.” cümlesindeki anlam ilişkisi nedir?',
              solution: [
                '“Ama” bağlacı iki yargıyı birbirine bağlıyor.',
                'Birinci yargı olumlu bir eylem, ikincisi bu eylemle çelişen bir değerlendirme.',
                'Bu, karşıtlık (zıtlık) ilişkisidir. Ayrıca ikinci bölüm öznel bir yargıdır.',
              ],
            },
          ],
        },
        {
          id: 'tur-u1-q', kind: 'quiz',
          title: '1. Ünite Değerlendirme Testi',
          subtitle: 'Sözcükte ve Cümlede Anlam',
          intro: 'Bu ünitede öğrendiklerinizi 8 soruyla ölçün. Cevaplarınız sonuç ekranında çözümleriyle birlikte gösterilecek.',
          questionIds: ['tur-001', 'tur-002', 'tur-003', 'tur-004', 'tur-005', 'tur-006', 'tur-007', 'tur-026'],
        },
      ],
    },
    {
      id: 'tur-u2',
      title: '2. Ünite — Paragraf',
      pages: [
        {
          id: 'tur-u2-p1', kind: 'content',
          title: 'Ana Düşünce ve Yardımcı Düşünce',
          subtitle: 'Paragrafın kalbini bulmak',
          blocks: [
            { id: 'b1', type: 'p', text: 'Paragraf, tek bir düşünce etrafında örülmüş cümleler topluluğudur. Bu tek düşünce, ana düşüncedir. Yardımcı düşünceler ise ana düşünceyi destekleyen, örnekleyen, açıklayan yan yargılardır.' },
            {
              id: 'b2', type: 'callout', variant: 'tanim', title: 'Ana düşünce nasıl bulunur?',
              text: 'Paragrafı okuduktan sonra kendinize şunu sorun: “Yazar bu paragrafı hangi tek cümleyi söylemek için yazdı?” Bu cümlenin yanıtı ana düşüncedir. Genellikle ilk ya da son cümlede gizlidir; bazen hiçbir cümlede açıkça yer almaz, çıkarılması gerekir.',
            },
            { id: 'b3', type: 'h3', text: 'Ana Düşünce Tuzağı' },
            {
              id: 'b4', type: 'list',
              items: [
                'Paragrafta geçen ama tek bir cümleyi karşılayan seçenek: yardımcı düşüncedir, ana düşünce değildir.',
                'Paragraftan daha geniş, “her insan”, “tüm dünya” gibi genellemeler: kapsam aşımıdır, yanlıştır.',
                'Paragrafta hiç geçmeyen bir bilgi içeren seçenek: doğrudan elenir.',
                'Doğru seçenek, paragrafın tamamını kapsar; ne eksik ne fazla.',
              ],
            },
            { id: 'b5', type: 'h3', text: 'Yardımcı Düşünce Soruları' },
            { id: 'b6', type: 'p', text: '“Aşağıdakilerden hangisine değinilmemiştir?” tipindeki sorularda seçenekleri tek tek paragrafta arayın. Dört seçeneğin karşılığını metinde bulacaksınız; bulamadığınız seçenek cevaptır. Bu, zaman alan ama garanti puan getiren bir tekniktir.' },
            {
              id: 'b7', type: 'example', title: 'Uygulama',
              question: 'Aşağıdaki paragrafın ana düşüncesini bulun: “Bir ağacı tanımak için gövdesine bakmak yetmez. Köklerinin hangi toprakta beslendiğini, dallarının hangi rüzgârla eğildiğini bilmek gerekir. İnsan da böyledir: Onu anlamak için yaşadığı yeri ve zamanı bilmelisiniz.”',
              solution: [
                'Paragrafta ağaç üzerinden bir benzetme kuruluyor.',
                'Son cümle benzetmenin uygulandığı yer: insan.',
                'Ana düşünce: İnsanı anlamak için içinde yetiştiği koşulları bilmek gerekir.',
              ],
            },
          ],
        },
        {
          id: 'tur-u2-p2', kind: 'content',
          title: 'Paragrafta Yapı',
          subtitle: 'Giriş, gelişme, sonuç ve akış',
          blocks: [
            { id: 'b1', type: 'p', text: 'Yeni nesil sorularda paragrafın anlamı kadar yapısı da sorulur. Paragrafı bir binaya benzetirsek: giriş cümlesi temel, gelişme cümleleri katlar, sonuç cümlesi çatıdır.' },
            {
              id: 'b2', type: 'table',
              headers: ['Bölüm', 'Özellikleri', 'İpucu'],
              rows: [
                ['Giriş', 'Kendinden önceki bir cümleye bağlanmaz, konuyu tanıtır.', 'Bağlaç ve zamirle başlamaz.'],
                ['Gelişme', 'Konuyu örnek, karşılaştırma, tanıkla açar.', '“Ayrıca, üstelik, örneğin” gibi bağlayıcılar.'],
                ['Sonuç', 'Yargıyı bağlar, özetler ya da öneri verir.', '“Kısacası, demek ki, sonuç olarak”.'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'ipucu', title: 'Akışı bozan cümle',
              text: 'Numaralanmış cümlelerden birinin akışı bozduğu sorularda, paragrafın konusunu bir kelimeyle belirleyin. Sonra her cümlenin o kelimeyle ilgisini kontrol edin. İlgisi kopan cümle cevaptır — genellikle konuyla yüzeysel benzerlik taşıdığı için dikkat gerektirir.',
            },
            { id: 'b4', type: 'h3', text: 'Paragrafı İkiye Bölme' },
            { id: 'b5', type: 'p', text: 'Bu soru tipinde bir metnin hangi cümleden itibaren yeni bir paragrafa geçtiği sorulur. İki paragrafın iki ayrı konusu olur. Konu değişiminin başladığı cümle, ikinci paragrafın ilk cümlesidir. O cümlenin bağlaç ya da zamirle başlamadığından emin olun.' },
            { id: 'b6', type: 'h3', text: 'Paragraf Tamamlama' },
            {
              id: 'b7', type: 'list',
              ordered: true,
              items: [
                'Boşluğun önündeki ve arkasındaki cümleyi dikkatle okuyun.',
                'Boşluk, bu iki cümle arasında anlam köprüsü kurmalıdır.',
                'Boşluktan sonra “bu nedenle, oysa, çünkü” gibi bir bağlayıcı varsa, boşluğa gelecek cümlenin niteliği belirlenmiş demektir.',
                'Seçeneği yerine koyup paragrafı yeniden okuyun; kulağa doğal gelmiyorsa yanlıştır.',
              ],
            },
          ],
        },
        {
          id: 'tur-u2-p3', kind: 'content',
          title: 'Anlatım Biçimleri ve Düşünceyi Geliştirme Yolları',
          subtitle: 'Yazar nasıl anlatıyor?',
          blocks: [
            { id: 'b1', type: 'h3', text: 'Dört Temel Anlatım Biçimi' },
            {
              id: 'b2', type: 'terms',
              items: [
                { term: 'Öyküleme', def: 'Olayı zaman akışı içinde anlatır. Eylem vardır, hareket vardır. “Kapıyı açtı, içeri girdi, ışığı yaktı.”' },
                { term: 'Betimleme', def: 'Görüntüyü sözcüklerle resmeder. Sıfatlar yoğundur, hareket azdır. “Uzun, kirli sakallı, çökük gözlü bir adamdı.”' },
                { term: 'Açıklama', def: 'Bilgi verir, öğretir. Tarafsız ve nesneldir. Ders kitabı dili budur.' },
                { term: 'Tartışma', def: 'Bir görüşü çürütüp kendi görüşünü savunur. “Oysa”, “ne var ki”, “bu doğru değil” ifadeleri sıktır.' },
              ],
            },
            { id: 'b3', type: 'h3', text: 'Düşünceyi Geliştirme Yolları' },
            {
              id: 'b4', type: 'table',
              headers: ['Yol', 'Nasıl anlaşılır?'],
              rows: [
                ['Tanımlama', '“… nedir?” sorusunun cevabı verilir.'],
                ['Örneklendirme', '“Örneğin”, “söz gelimi”, “mesela” ile somut örnek verilir.'],
                ['Karşılaştırma', 'İki şeyin benzer ya da farklı yönleri sıralanır.'],
                ['Tanık gösterme', 'Uzman bir kişinin sözü tırnak içinde aktarılır.'],
                ['Sayısal verilerden yararlanma', 'Yüzde, oran, istatistik kullanılır.'],
                ['Benzetme', 'Anlatılan şey, bilinen başka bir şeye benzetilir.'],
              ],
            },
            {
              id: 'b5', type: 'callout', variant: 'dikkat', title: 'Tanık gösterme ≠ Örneklendirme',
              text: 'Tanık göstermede mutlaka bir kişinin sözü alıntılanır ve o kişinin adı verilir. Yalnızca bir örnek verilmişse bu örneklendirmedir. LGS’de bu ikisi bilinçli olarak karıştırılır.',
            },
            {
              id: 'b6', type: 'example', title: 'Örnek',
              question: '“Sabah yürüyüşü kalbi güçlendirir. Nitekim Dünya Sağlık Örgütü, haftada 150 dakikalık yürüyüşün kalp hastalığı riskini %30 azalttığını bildiriyor.” Hangi düşünceyi geliştirme yolu kullanılmıştır?',
              solution: [
                'Bir kurumun görüşüne başvurulmuş: tanık gösterme.',
                'Ayrıca %30 ve 150 dakika sayıları verilmiş: sayısal verilerden yararlanma.',
                'İki yol birlikte kullanılmıştır.',
              ],
            },
          ],
        },
        {
          id: 'tur-u2-q', kind: 'quiz',
          title: '2. Ünite Değerlendirme Testi',
          subtitle: 'Paragraf',
          intro: 'Paragraf sorularında hız kadar dikkat de önemlidir. Acele etmeyin; her seçeneği metinde arayın.',
          questionIds: ['tur-009', 'tur-010', 'tur-011', 'tur-025', 'tur-008', 'tur-028'],
        },
      ],
    },
    {
      id: 'tur-u3',
      title: '3. Ünite — Fiilimsiler ve Cümle Bilgisi',
      pages: [
        {
          id: 'tur-u3-p1', kind: 'content',
          title: 'Fiilimsiler',
          subtitle: 'Fiilden doğan, isim gibi davranan yapılar',
          blocks: [
            { id: 'b1', type: 'p', text: 'Fiilimsi (eylemsi), fiil kök ya da gövdesine özel ekler getirilerek türetilen; ancak cümlede isim, sıfat veya zarf görevinde kullanılan sözcüktür. Fiilimsiler kip ve kişi eki almaz; bu yüzden yüklem olamazlar (ek-fiil almadıkları sürece).' },
            {
              id: 'b2', type: 'table',
              caption: 'Üç fiilimsi türü ve ekleri',
              headers: ['Tür', 'Ekleri', 'Görevi', 'Örnek'],
              rows: [
                ['İsim-fiil (mastar)', '-mak/-mek, -ma/-me, -ış/-iş', 'İsim', 'Yüzmeyi severim.'],
                ['Sıfat-fiil (ortaç)', '-an/-en, -ası, -mez, -ar, -dik, -ecek, -miş', 'Sıfat', 'Kırılan cam'],
                ['Zarf-fiil (ulaç)', '-ip, -arak, -ınca, -ken, -madan, -alı, -dıkça, -casına, -meksizin', 'Zarf', 'Koşarak geldi.'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'ipucu', title: 'Ezber cümlesi',
              text: 'Sıfat-fiil eklerini “-AN, -ASI, -MEZ, -AR, -DIK, -ECEK, -MİŞ” diye sırayla okuyarak ezberleyin. Cümlenin baş harfleri: Anası Mezarda Diken Ekmiş.',
            },
            {
              id: 'b4', type: 'callout', variant: 'dikkat', title: 'Kalıcı isim tuzağı',
              text: 'Bazı fiilimsiler kalıplaşıp kalıcı isim olur: “dondurma”, “çakmak”, “dolmuş”, “gecekondu”, “danışman”. Bunlar artık fiilimsi sayılmaz; varlık adıdır. Soruda “kaç fiilimsi vardır?” diye sorulduğunda bunları saymayın.',
            },
            {
              id: 'b5', type: 'example', title: 'Örnek',
              question: '“Yürüyerek gelen çocuk, susamış olduğunu söyleyince ona su verdik.” cümlesindeki fiilimsileri bulun.',
              solution: [
                '“Yürüyerek” → -arak zarf-fiil eki (zarf görevinde).',
                '“Gelen” → -en sıfat-fiil eki (“çocuk” adını niteliyor).',
                '“Söyleyince” → -ınca zarf-fiil eki.',
                '“Susamış” burada sıfat-fiil değil, birleşik fiilin parçasıdır. Toplam 3 fiilimsi vardır.',
              ],
            },
          ],
        },
        {
          id: 'tur-u3-p2', kind: 'content',
          title: 'Cümlenin Ögeleri',
          subtitle: 'Yüklemden başlayarak soru sorma tekniği',
          blocks: [
            { id: 'b1', type: 'p', text: 'Cümlenin ögelerini bulmanın tek doğru yolu vardır: Önce yüklemi bulun, sonra bütün soruları yükleme sorun. Sorulara cümlenin başından değil, yüklemden hareketle cevap arayın.' },
            {
              id: 'b2', type: 'list', ordered: true,
              items: [
                'Yüklem: Cümledeki yargıyı bildiren ögedir. Genellikle sondadır. “Ne yapıldı? Ne oldu? Nedir?”',
                'Özne: Yükleme “Kim? Ne?” sorulur. İşi yapan veya olan.',
                'Belirtili nesne: “Kimi? Neyi?” — hâl eki almıştır.',
                'Belirtisiz nesne: “Ne?” — hâl eki almamıştır.',
                'Dolaylı tümleç: “Kime? Kimde? Kimden? Nereye? Nerede? Nereden?”',
                'Zarf tümleci: “Nasıl? Ne zaman? Ne kadar? Niçin?”',
                'Edat tümleci: “Kiminle? Ne ile?”',
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Gizli özne ve sözde özne',
              text: 'Cümlede özne görünmüyorsa yükleme bakarak bulunabiliyorsa buna gizli özne denir: “Kitabı okudum.” → (ben). Fiil edilgense ve işi yapan belli değilse, öznenin yerini tutan ögeye sözde özne denir: “Cam kırıldı.” → cam, sözde öznedir.',
            },
            {
              id: 'b4', type: 'example', title: 'Çözümlü örnek',
              question: '“Dün akşam kardeşim bahçedeki kediye süt verdi.” cümlesinin ögelerini bulun.',
              solution: [
                'Yüklem: verdi',
                'Özne (kim verdi?): kardeşim',
                'Belirtisiz nesne (ne verdi?): süt',
                'Dolaylı tümleç (kime verdi?): bahçedeki kediye',
                'Zarf tümleci (ne zaman verdi?): dün akşam',
              ],
            },
            {
              id: 'b5', type: 'callout', variant: 'bilgi', title: 'Ara söz',
              text: 'İki virgül ya da iki kısa çizgi arasında verilen, bir ögeyi açıklayan söz öbeğine ara söz denir. Ara söz, açıkladığı ögenin bir parçası sayılır; tek başına öge olamaz.',
            },
          ],
        },
        {
          id: 'tur-u3-p3', kind: 'content',
          title: 'Fiilde Çatı ve Cümle Çeşitleri',
          subtitle: 'Özne–yüklem ve nesne–yüklem ilişkisi',
          blocks: [
            { id: 'b1', type: 'h3', text: 'Öznesine Göre Çatı' },
            {
              id: 'b2', type: 'terms',
              items: [
                { term: 'Etken', def: 'Özne, işi kendisi yapar: “Ali camı kırdı.”' },
                { term: 'Edilgen', def: 'İşi yapan belli değildir, fiil -l veya -n eki alır: “Cam kırıldı.”' },
                { term: 'Dönüşlü', def: 'Özne işi kendi üzerinde yapar, -l/-n eki vardır: “Çocuk yıkandı.”' },
                { term: 'İşteş', def: 'İş karşılıklı ya da birlikte yapılır, -ş eki vardır: “Arkadaşlar bakıştı.”' },
              ],
            },
            { id: 'b3', type: 'h3', text: 'Nesnesine Göre Çatı' },
            {
              id: 'b4', type: 'list',
              items: [
                'Geçişli: Nesne alabilir. Yükleme “neyi/kimi” sorulabiliyorsa geçişlidir. “Kitabı okudu.”',
                'Geçişsiz: Nesne alamaz. “Çocuk uyudu.”',
                'Ettirgen: Geçişsiz fiil, -r/-t/-dır ekleriyle geçişli yapılır. “uyudu → uyuttu”',
                'Oldurgan: Geçişlilik derecesi artırılır. “yazdı → yazdırdı”',
              ],
            },
            {
              id: 'b5', type: 'callout', variant: 'ipucu', title: 'Kesin yöntem',
              text: 'Geçişlilik testi için fiilin başına “onu” getirin. Anlamlı oluyorsa geçişlidir. “Onu okudu” ✓ geçişli. “Onu uyudu” ✗ geçişsiz.',
            },
            { id: 'b6', type: 'h3', text: 'Yapısına Göre Cümleler' },
            {
              id: 'b7', type: 'table',
              headers: ['Tür', 'Özellik', 'Örnek'],
              rows: [
                ['Basit', 'Tek yüklem, yan cümlecik yok', 'Bugün hava çok güzel.'],
                ['Birleşik', 'İçinde fiilimsi veya yan cümlecik var', 'Gelen misafirler salona geçti.'],
                ['Sıralı', 'Virgül/noktalı virgülle bağlı birden çok cümle', 'Kapıyı açtı, içeri girdi.'],
                ['Bağlı', '“ve, ama, fakat” gibi bağlaçla bağlı', 'Çalıştı ama başaramadı.'],
              ],
            },
          ],
        },
        {
          id: 'tur-u3-q', kind: 'quiz',
          title: '3. Ünite Değerlendirme Testi',
          subtitle: 'Fiilimsiler ve Cümle Bilgisi',
          questionIds: ['tur-012', 'tur-013', 'tur-027', 'tur-014', 'tur-015', 'tur-016', 'tur-017'],
        },
      ],
    },
    {
      id: 'tur-u4',
      title: '4. Ünite — Yazım, Noktalama ve Anlatım',
      pages: [
        {
          id: 'tur-u4-p1', kind: 'content',
          title: 'Yazım Kuralları',
          subtitle: 'En çok yanlış yapılan on kural',
          blocks: [
            {
              id: 'b1', type: 'list', ordered: true,
              items: [
                'Bağlaç olan “de/da” her zaman ayrı yazılır ve “ta/te” biçiminde sertleşmez: “Sen de gel.”',
                'Bulunma hâli eki “-de/-da” bitişik yazılır ve ünsüz benzeşmesine uğrar: “kitapta”, “sınıfta”.',
                'Bağlaç olan “ki” ayrı yazılır: “Biliyorum ki gelecek.” Ancak “sanki, belki, mademki, oysaki, hâlbuki, çünkü, meğerki” kalıplaşmıştır, bitişik yazılır.',
                'Soru eki “mi” her zaman ayrı yazılır, kendinden sonra gelen eki bitişik alır: “Geliyor musun?”',
                'Özel adlara gelen çekim ekleri kesme işaretiyle ayrılır: “Ankara’ya”, “Ali’nin”.',
                'Kurum ve kuruluş adlarına gelen ekler kesmeyle ayrılmaz: “Türk Dil Kurumundan”.',
                'Dil, din, millet adlarına gelen ekler kesmeyle ayrılmaz: “Türkçeyi”, “Müslümanlıkta”.',
                'Sayılar metin içinde yazıyla yazılır; ancak tarih, saat ve ölçüde rakam kullanılır.',
                'Pekiştirmeli sözcükler bitişik yazılır: “apaçık”, “bembeyaz”, “sapasağlam”.',
                '“Herkes” daima “s” ile; “yanlış”, “yalnız”, “sürpriz”, “eşofman” yaygın yanlışlardır.',
              ],
            },
            {
              id: 'b2', type: 'callout', variant: 'ipucu', title: 'Bağlaç mı ek mi?',
              text: '“de/da”yı cümleden çıkarın. Cümle anlamlı kalıyorsa bağlaçtır, ayrı yazılır. Çıkarınca anlam bozuluyorsa ektir, bitişik yazılır. Aynı test “ki” için de geçerlidir.',
            },
            {
              id: 'b3', type: 'table',
              caption: 'Sık yapılan yazım yanlışları',
              headers: ['Yanlış', 'Doğru'],
              rows: [
                ['herkez', 'herkes'], ['yalnış', 'yanlış'], ['yanlız', 'yalnız'],
                ['süpriz', 'sürpriz'], ['eşortman', 'eşofman'], ['kirbit', 'kibrit'],
                ['Türkçe’yi', 'Türkçeyi'], ['bir kaç', 'birkaç'], ['her hangi', 'herhangi'],
              ],
            },
          ],
        },
        {
          id: 'tur-u4-p2', kind: 'content',
          title: 'Noktalama İşaretleri',
          subtitle: 'Anlamı belirleyen küçük işaretler',
          blocks: [
            { id: 'b1', type: 'p', text: 'Noktalama işaretleri süs değil, anlamın parçasıdır. “Yaşlı adama bakmadan geçti.” ile “Yaşlı, adama bakmadan geçti.” cümlelerinin özneleri farklıdır. Tek bir virgül anlamı değiştirir.' },
            {
              id: 'b2', type: 'table',
              headers: ['İşaret', 'Başlıca kullanımı'],
              rows: [
                ['Nokta (.)', 'Cümle sonu, kısaltmalar, tarih ayrımı (12.09.2026), sıra sayıları (5.)'],
                ['Virgül (,)', 'Eş görevli sözcükler, sıralı cümleler, ara sözler, özneyi vurgulama, bağlaçlardan önce'],
                ['Noktalı virgül (;)', 'Virgülle ayrılmış gruplar arasında, “ama/fakat/ancak” öncesinde'],
                ['İki nokta (:)', 'Açıklama, örnek ya da alıntı öncesi'],
                ['Üç nokta (…)', 'Tamamlanmamış cümle, sözün sürdüğünü gösterme'],
                ['Soru işareti (?)', 'Soru cümlesi sonu; şüphe bildirilen tarihlerde'],
                ['Kesme (’)', 'Özel adlara gelen çekim ekleri'],
                ['Kısa çizgi (-)', 'Satır sonu bölme, heceleme, ekleri gösterme'],
                ['Uzun çizgi (—)', 'Konuşma çizgisi; tiyatro ve diyaloglarda'],
              ],
            },
            {
              id: 'b3', type: 'callout', variant: 'dikkat', title: 'Virgül tuzağı',
              text: 'Metin içinde “ve, veya, ile” bağlaçlarından önce virgül konmaz. Ayrıca özne ile yüklem arasına doğrudan virgül konmaz — yalnızca özneyi vurgulamak istediğinizde konur.',
            },
          ],
        },
        {
          id: 'tur-u4-p3', kind: 'content',
          title: 'Anlatım Bozuklukları',
          subtitle: 'Anlama ve yapıya dayalı hatalar',
          blocks: [
            { id: 'b1', type: 'h3', text: 'Anlama Dayalı Bozukluklar' },
            {
              id: 'b2', type: 'list',
              items: [
                'Gereksiz sözcük kullanımı: “Yukarı doğru yükseldi.”',
                'Anlamca çelişen sözler: “Kesinlikle sanırım gelir.”',
                'Sözcüğün yanlış anlamda kullanılması: “Yolun çukurları azalmıştı.” (azalmak ≠ azalmak/örtülmek)',
                'Deyim yanlışlığı: Deyimi anlamına uymayan yerde kullanmak.',
                'Mantık hatası: “Hem en iyi hem de ikinci sıradaydı.”',
                'Sıralama yanlışlığı: “Yaralı hastaneye kaldırıldı ve ambulans çağrıldı.”',
              ],
            },
            { id: 'b3', type: 'h3', text: 'Yapıya Dayalı Bozukluklar' },
            {
              id: 'b4', type: 'list',
              items: [
                'Özne eksikliği: “Çocuklara oyuncak dağıtıldı ve çok sevindiler.”',
                'Nesne eksikliği: “Kitabı aldım ve rafa koydum.” ✓ / “Onu sevdim ve kucakladım.” yapısında ortak nesne uyumu aranır.',
                'Tümleç eksikliği: “Ne kendisi gitti ne de haber verdi.” (kime?)',
                'Yüklem eksikliği: “Ben çayı, o kahveyi sever.” → “Ben çayı severim, o kahveyi sever.”',
                'Özne–yüklem uyumsuzluğu: “Öğrenciler geldi.” ✓ / “Kitaplar geldiler.” ✗ (cansız çoğullar tekil yüklem alır)',
                'Tamlama yanlışlığı: “ekonomik ve sosyal sorunları” ✓ / “ekonomi ve sosyal sorunları” ✗',
              ],
            },
            {
              id: 'b5', type: 'example', title: 'Örnek',
              question: '“Sınıfta hiç kimse ödevini yapmamış ve öğretmene mazeret bildirdiler.” cümlesindeki bozukluğu düzeltin.',
              solution: [
                'Birinci yüklemin öznesi “hiç kimse” (tekil), ikinci yüklem “bildirdiler” (çoğul).',
                'Özne–yüklem uyumsuzluğu ve mantık çelişkisi vardır.',
                'Düzeltme: “Sınıfta hiç kimse ödevini yapmamış, herkes öğretmene mazeret bildirmiş.”',
              ],
            },
          ],
        },
        {
          id: 'tur-u4-p4', kind: 'content',
          title: 'Söz Sanatları',
          subtitle: 'Anlatımı güzelleştiren yollar',
          blocks: [
            {
              id: 'b1', type: 'terms',
              items: [
                { term: 'Benzetme (teşbih)', def: 'Bir varlığı, ortak özelliği olan başka bir varlığa benzetmek: “Sesi bülbül gibiydi.”' },
                { term: 'Kişileştirme (teşhis)', def: 'İnsana ait özellikleri başka varlıklara vermek: “Ağaçlar rüzgârla fısıldaştı.”' },
                { term: 'Konuşturma (intak)', def: 'İnsan dışı varlığı konuşturmak: “Kedi bana ‘açım’ dedi.” Konuşturma varsa kişileştirme de vardır.' },
                { term: 'Abartma (mübalağa)', def: 'Bir şeyi olduğundan çok göstermek: “Gözyaşlarıyla dereleri doldurdu.”' },
                { term: 'Karşıtlık (tezat)', def: 'Karşıt kavramları bir arada kullanmak: “Ağlarken gülüyordu.”' },
                { term: 'Dolaylama', def: 'Tek sözcükle anlatılabileni birden çok sözcükle anlatmak: “ormanlar kralı” (aslan).' },
              ],
            },
            {
              id: 'b2', type: 'callout', variant: 'bilgi', title: 'Sınavda ayırt etme',
              text: 'Kişileştirme varsa mutlaka insana ait bir eylem/duygu başka bir varlığa verilmiştir. Benzetmede ise “gibi, kadar, sanki” edatları ya da benzetme yönü açıkça bulunur.',
            },
            {
              id: 'b3', type: 'quote',
              text: 'Bir gemi bekliyor liman kıyısında,\nDalgalar fısıldıyor kulağına yolları.',
              source: 'Adsız bir defter sayfasından',
            },
          ],
        },
        {
          id: 'tur-u4-q', kind: 'quiz',
          title: '4. Ünite Değerlendirme Testi',
          subtitle: 'Yazım, Noktalama ve Anlatım',
          questionIds: ['tur-018', 'tur-019', 'tur-020', 'tur-021', 'tur-022', 'tur-023', 'tur-024'],
        },
      ],
    },
  ],
}
